spring:
  profiles:
    active: qa

logging:
  level:
    app: TRACE

redis:
  membershipConnection: redis://core-dev-redis.pid24g.0001.usw2.cache.amazonaws.com:6379/1
  membershipTTL: 7776000
  partnerConnection: redis://core-dev-redis.pid24g.0001.usw2.cache.amazonaws.com:6379/0
  partnerTTL: 7776000

