---
kafkaAuth:
  username: ENC(3qpeUILsCYG+FkbZbJBjB9CyXrs21xDN+KlPfxQiX/0=)
  password: ENC(2wBkQZbnmRoicoHjcIlgpd0KIM5lJ62JSqqxf+cGE5QKL0DcLHGRICnyj70WDtYbQ4uYhCoAvJcN6LjMsISJc6JPhsTE8d6X4NTWKTC6AnY=)

spring:
  profiles:
    active: prod-aws-east
  kafka:
    listener:
      concurrency=: 1
    properties:
      request:
        timeout:
          ms: 60000
      ssl:
        protocol: TLSv1.2
        enabled:
          protocols: TLSv1.2
        truststore:
          type: JKS
        endpoint:
          identification:
            algorithm: HTTPS
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="4H4YY5F3FLITE2KG" password="gwL8gRW9jXoVLodcjPq7UM4Lp1yjrkt8rTBfAvtbXmgNO7sTwJwRV/VLORHZsmkH";
        mechanism: PLAIN
      security:
        protocol: SASL_SSL
    consumer:
      bootstrap-servers: ['pkc-4n7ze.us-west-2.aws.confluent.cloud:9092']
      group-id: membership-consumer-prod-aws-east
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    app: INFO

redis:
  membershipConnection: redis://core-prod-membership-new.xusj1p.clustercfg.use1.cache.amazonaws.com:6379
  membershipTTL: 5184000
  partnerConnection: redis://core-prod-partner.xusj1p.clustercfg.use1.cache.amazonaws.com:6379
  partnerTTL: 15552000
  topologyRefreshHours: 1
  clientShutdownSeconds: 60
  requestTimeoutSeconds: 10

membership:
  oracleConsumer: false
  membershipConsumer: true

app:
  membershipDataExpirationWindowSeconds: 7776000