---
kafkaAuth:
  username: ENC(3qpeUILsCYG+FkbZbJBjB9CyXrs21xDN+KlPfxQiX/0=)
  password: ENC(2wBkQZbnmRoicoHjcIlgpd0KIM5lJ62JSqqxf+cGE5QKL0DcLHGRICnyj70WDtYbQ4uYhCoAvJcN6LjMsISJc6JPhsTE8d6X4NTWKTC6AnY=)

spring:
  profiles:
    active: prod-aws-east
  kafka:
    properties:
      client:
        id: ${messageHub.username}${messageHub.password}
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${kafkaAuth.username}" password="${kafkaAuth.password}";
    consumer:
      bootstrap-servers: ['pkc-4n7ze.us-west-2.aws.confluent.cloud:9092']
      group-id: membership-consumer-prod-aws-east
      auto-offset-reset: earliest

logging:
  level:
    app: INFO

redis:
  membershipConnection: redis://core-prod-membership.xusj1p.clustercfg.use1.cache.amazonaws.com:6379
  membershipTTL: 5184000
  partnerConnection: redis://core-prod-partner.xusj1p.clustercfg.use1.cache.amazonaws.com:6379
  partnerTTL: 15552000
  topologyRefreshHours: 1
  clientShutdownSeconds: 60
  requestTimeoutSeconds: 10
