spring:
  jpa:
    hibernate:
      ddl-auto=none: false
  profiles:
    active: dev
  application:
    name: membership-consumer
    spring.http.encoding.charset: UTF-8
    spring.http.encoding.enabled: true
    spring.http.encoding.force: true

logging:
  path: ./log
  level:
    app: DEBUG

server:
  port: 8080
  connection-timeout: 600000


management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
      path-mapping:
        health: health

kafka:
  subscribe-topic: membership-updates

redis:
  membershipConnectionTpa: redis://core-dev-redis-1.pid24g.clustercfg.usw2.cache.amazonaws.com:6379
  membershipTTL: 7776000
  partnerConnection: redis://core-dev-redis-0.pid24g.clustercfg.usw2.cache.amazonaws.com:6379
  partnerTTL: 7776000
  requestTimeoutSeconds: 10
  topologyRefreshHours: 1
  clientShutdownSeconds: 10

aerospike:
  hostnames: [localhost]
  port: 3000
  namespace: rtb
  set-name: household_profile
  ttl-seconds: 7776000
