---
spring:
  kafka:
    listener:
      concurrency=: 1
    consumer:
      bootstrap-servers: [ 'b-1.mskrtbdev2.apc8bs.c14.kafka.us-west-2.amazonaws.com:9092','b-2.mskrtbdev2.apc8bs.c14.kafka.us-west-2.amazonaws.com:9092' ]
      group-id: membership-consumer-dev-frequency-west
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


logging:
  level:
    app: INFO

redis:
  recencyConnection: redis://core-dev-recency.pid24g.clustercfg.usw2.cache.amazonaws.com:6379
  frequencyCapConnection: redis://core-dev-frequency-caps.pid24g.clustercfg.usw2.cache.amazonaws.com:6379
  topologyRefreshHours: 1
  clientShutdownSeconds: 60
  requestTimeoutSeconds: 10

aerospike:
  hostnames: [localhost]
  port: 3000
  namespace: rtb
  set-name: household-profile
  ttl-seconds: 5184000

membership:
  oracleConsumer: false
  membershipConsumer: false
  impressionConsumer: true
  recencyConsumer: false

app:
  recencySha: d0092a4b68842a839daa2cf020983b8c0872f0db
  recencyDeviceIDTTLSeconds: 604800
  recencyExpirationWindowMilliSeconds: 604800000
  frequencySha: 22242d94dc42e02a0fb3c21bfaa0d77f3237d869
  frequencyDeviceIDTTLSeconds: 3600000
  frequencyExpirationWindowMilliSeconds: 864000000