spring:
  profiles:
    active: dev
  kafka:
    consumer:
      group-id: membership-consumer-dev2

logging:
  level:
    app: TRACE

redis:
  membershipConnection: redis://core-dev-redis-1.pid24g.clustercfg.usw2.cache.amazonaws.com:6379
  membershipTTL: 7776000
  partnerConnection: redis://core-dev-redis-0.pid24g.clustercfg.usw2.cache.amazonaws.com:6379
  partnerTTL: 7776000
  topologyRefreshHours: 1
  clientShutdownSeconds: 60
  requestTimeoutSeconds: 10
