spring:
  profiles:
    active: prod

logging:
  level:
    app: INFO

redis:
  membershipConnection: redis://core-prod-membership.pid24g.clustercfg.usw2.cache.amazonaws.com:6379
  membershipTTL: 7776000
  partnerConnection: redis://core-prod-partner.pid24g.clustercfg.usw2.cache.amazonaws.com:6379
  partnerTTL: 7776000
  topologyRefreshHours: 1
  clientShutdownSeconds: 60
  requestTimeoutSeconds: 10
