---
spring:
  profiles:
    active: prod-oracle-west
  kafka:
    listener:
      concurrency=: 1
    consumer:
      bootstrap-servers: ['b-3.msk-rtb-prod-2.ifib9x.c10.kafka.us-west-2.amazonaws.com:9092','b-4.msk-rtb-prod-2.ifib9x.c10.kafka.us-west-2.amazonaws.com:9092','b-7.msk-rtb-prod-2.ifib9x.c10.kafka.us-west-2.amazonaws.com:9092']
      group-id: membership-consumer-prod-oracle-west
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


logging:
  level:
    app: INFO

redis:
  membershipConnection: redis://core-prod-membership-new.pid24g.clustercfg.usw2.cache.amazonaws.com:6379
  membershipTTL: 5184000
  partnerConnection: redis://core-prod-partner.pid24g.clustercfg.usw2.cache.amazonaws.com:6379
  householdConnection: redis://core-prod-household-score.pid24g.clustercfg.usw2.cache.amazonaws.com:6379
  recencyConnection: redis://core-prod-recency.pid24g.clustercfg.usw2.cache.amazonaws.com:6379
  partnerTTL: 15552000
  topologyRefreshHours: 1
  clientShutdownSeconds: 60
  requestTimeoutSeconds: 10

membership:
  oracleConsumer: true
  membershipConsumer: false

app:
  membershipDataExpirationWindowSeconds: 7776000