---
spring:
  profiles:
    active: prod-oracle-east
  kafka:
    listener:
      concurrency=: 1
    consumer:
      bootstrap-servers: ['b-1.msk-rtb-prod.gsn3vr.c2.kafka.us-east-1.amazonaws.com:9092,b-2.msk-rtb-prod.gsn3vr.c2.kafka.us-east-1.amazonaws.com:9092,b-3.msk-rtb-prod.gsn3vr.c2.kafka.us-east-1.amazonaws.com:9092']
      group-id: membership-consumer-prod-oracle-east
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    app: INFO

redis:
  membershipConnection: redis://core-prod-membership.xusj1p.clustercfg.use1.cache.amazonaws.com:6379
  membershipTTL: 5184000
  partnerConnection: redis://core-prod-partner.xusj1p.clustercfg.use1.cache.amazonaws.com:6379
  partnerTTL: 15552000
  topologyRefreshHours: 1
  clientShutdownSeconds: 60
  requestTimeoutSeconds: 10

membership:
  oracleConsumer: true
  membershipConsumer: false

app:
  membershipDataExpirationWindowSeconds: 7776000