---
spring:
  kafka:
    listener:
      concurrency=: 1
    properties:
      ssl:
        protocol: TLSv1.2
        enabled:
          protocols: TLSv1.2
        truststore:
          type: JKS
        endpoint:
          identification:
            algorithm: HTTPS
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="4H4YY5F3FLITE2KG" password="gwL8gRW9jXoVLodcjPq7UM4Lp1yjrkt8rTBfAvtbXmgNO7sTwJwRV/VLORHZsmkH";
        mechanism: PLAIN
      security:
        protocol: SASL_SSL
    consumer:
      bootstrap-servers: [ 'pkc-4n7ze.us-west-2.aws.confluent.cloud:9092' ]
      group-id: membership-consumer-prod-recency-west
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: [ 'pkc-4n7ze.us-west-2.aws.confluent.cloud:9092' ]
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3

logging:
  level:
    app: INFO

redis:
  membershipConnectionTpa: redis://core-prod-membership-compression.pid24g.clustercfg.usw2.cache.amazonaws.com:6379
  membershipTTL: 5184000
  deviceInfoConnection: redis://rtb-prod-device-info.pid24g.clustercfg.usw2.cache.amazonaws.com:6379
  recencyConnection: redis://core-prod-recency.pid24g.clustercfg.usw2.cache.amazonaws.com:6379
  frequencyCapConnection: redis://core-prod-frequency-caps.pid24g.clustercfg.usw2.cache.amazonaws.com:6379
  partnerTTL: 15552000
  topologyRefreshHours: 1
  clientShutdownSeconds: 60
  requestTimeoutSeconds: 10

membership:
  oracleConsumer: false
  membershipConsumer: false
  impressionConsumer: false
  recencyConsumer: true

app:
  recencySha: d0092a4b68842a839daa2cf020983b8c0872f0db
  recencyDeviceIDTTLSeconds: 2592000
  recencyExpirationWindowMilliSeconds: 2592000000
  frequencySha: ebdab639a5a6a3e9781cb71fedf413cb9485adc5
  frequencyDeviceIDTTLSeconds: 3600000
  frequencyExpirationWindowMilliSeconds: 864000000
