spring:
  kafka:
    producer:
      bootstrap-servers: [ 'localhost:9092' ]
      key-serializer: org.apache.kafkaConf.common.serialization.StringSerializer
      value-serializer: org.apache.kafkaConf.common.serialization.StringSerializer
      retries: 3
    consumer:
      bootstrap-servers: ['localhost:9092']
      group-id: membership-consumer
      auto-offset-reset: latest
      key-deserializer: org.apache.kafkaConf.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafkaConf.common.serialization.StringDeserializer

logging:
  level:
    app: TRACE

redis:
  recencyConnection: redis://localhost:6399
  frequencyCapConnection: redis://localhost:6398
  topologyRefreshHours: 1
  clientShutdownSeconds: 60
  requestTimeoutSeconds: 10

aerospike:
  hostnames: localhost
  port: 3000
  namespace: rtb
  set-name: household-profile
  ttl-seconds: 5184000

membership:
  oracleConsumer: false
  membershipConsumer: true
  impressionConsumer: false
  recencyConsumer: false

app:
  recencySha: d0092a4b68842a839daa2cf020983b8c0872f0db
  recencyDeviceIDTTLSeconds: 604800
  recencyExpirationWindowMilliSeconds: 604800000
  frequencySha: 22242d94dc42e02a0fb3c21bfaa0d77f3237d869
  frequencyDeviceIDTTLSeconds: 3600000
  frequencyExpirationWindowMilliSeconds: 864000000