replicaCount: 1
nameSpace: qa-ads
image:
  repository: steelhousedev/membership-consumer
  tag: qa-latest
  pullPolicy: Always
service:
  type: ClusterIP
  annotations:
    iam.amazonaws.com/role: core-dev-dynamo-access-pod-role
    iam.amazonaws.com/permitted: ".*"
  name: membership-consumer
  externalPort: 80
  internalPort: 8080
  probePath: /health
  domain: coredev.west2.steelhouse.com
ingress:
  enabled: true
  host: membership-consumer.coredev.west2.steelhouse.com
  labels:
    traffic-type: internal
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/alias: "true"
    external-dns.alpha.kubernetes.io/target: traefik.coredev.west2.steelhouse.com
resources:
  limits:
   cpu: 4000m
   memory: 3Gi
  requests:
   cpu: 4000m
   memory: 3Gi
env:
  - name: SPRING_PROFILES_ACTIVE
    value: qa
imagePullSecrets: codefresh-generated-docker.io-dockerhub-qa-targeting
istio:
  enabled: false




