replicaCount: 3
nameSpace: prod-ads
image:
  repository: steelhousedev/membership-consumer
  tag: prod-latest
  pullPolicy: Always
service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    external-dns.alpha.kubernetes.io/hostname: membership-consumer.coreprod.west2.steelhouse.com
    iam.amazonaws.com/role: core-dev-dynamo-access-pod-role
    iam.amazonaws.com/permitted: ".*"
  name: membership-consumer
  externalPort: 80
  internalPort: 8080
  probePath: /health
  domain: coreprod.west2.steelhouse.com
ingress:
  enabled: true
  labels:
    traffic-type: internal
resources:
  limits:
   cpu: 2000m
   memory: 4Gi
  requests:
   cpu: 2000m
   memory: 4Gi
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"
  - name: SECURITY_BASIC_ENABLED
    value: "false"
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"

imagePullSecrets: codefresh-generated-docker.io-dockerhub-prod-pixel
istio:
  enabled: false
