name: Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build-test:
    name: Build & test the codebase
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew clean test jacocoTestReport
      - name: Upload jacoco test report artifact
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-test-coverage-report
          path: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
  codacy-uploads:
    name: Upload jacoco test coverage report to codacy
    needs: build-test
    runs-on: ubuntu-latest
    env:
      CODACY_ACCOUNT_API_TOKEN: CfZGn11TIA2dcBhQNK8v
      CODACY_ORG_NAME: SteelHouse
      CODACY_GIT_PROVIDER: gh
    steps:
      - name: Download jacoco test report artifact
        uses: actions/download-artifact@v3
        with:
          name: jacoco-test-coverage-report
      - name: Get current branch name
        id: branch-name
        uses: tj-actions/branch-names@v7
      - name: Enable branch analysis in Codacy
        run: |
          curl -v -X PATCH https://app.codacy.com/api/v3/organizations/gh/SteelHouse/repositories/${{ github.event.repository.name }}/branches/"$(echo ${{ steps.branch-name.outputs.current_branch }} | sed 's/\//%2F/g')" \
            -H 'Content-Type: application/json' \
            -H 'Accept: application/json' \
            -H 'api-token: ${{ env.CODACY_ACCOUNT_API_TOKEN}}' \
            -d '{"isEnabled": true}'
      - name: Upload jacoco test coverage report to codacy
        env:
          CODACY_API_TOKEN: ${{ env.CODACY_ACCOUNT_API_TOKEN }}
          CODACY_ORGANIZATION_PROVIDER: ${{ env.CODACY_GIT_PROVIDER }}
          CODACY_USERNAME: ${{ env.CODACY_ORG_NAME }}
          CODACY_PROJECT_NAME: ${{ github.event.repository.name }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r jacocoTestReport.xml